import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Zion Griffin's Portfolio`,
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      {/* 
        <head /> will contain the components returned by the nearest parent head.tsx. 
      */}
      <body className={inter.className}>
        <nav className="flex items-center justify-between flex-wrap bg-slate-900 p-2">
          <ul className="flex border-b">
            <li className="-mb-px mr-1">
              <a className="bg-slate-900 inline-block border-l border-t border-r rounded-t py-2 px-4 text-blue-700 font-semibold" href="/">About Me</a>
            </li>
            <li className="mr-1">
              <a className="bg-slate-900 inline-block py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold" href="/projects">Projects</a>
            </li>
            <li className="mr-1">
              <a className="bg-slate-900 inline-block py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold" href="/contact">Contact</a>
            </li>
          </ul>
          <img src='icon.ico'></img>
          <h2 className='pr-6'>Zion Griffin's Portfolio</h2>
        </nav>
        {children}
      </body>
    </html>
  )
}
