import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
// import { usePathname } from 'next/navigation'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: `Zion Griffin's Portfolio`,
  description: 'Generated by create next app',
}
var pathName = 'about';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // const pathName = usePathname();
  // console.log(pathName);
  return (
    <html lang="en">

      {/* 
        <head /> will contain the components returned by the nearest parent head.tsx. 
      */}
      <body className={inter.className}>
        <nav className="flex items-center place-content-center place-content-between flex-wrap backdrop-blur-lg sticky top-0 p-2">
          <ul className="flex border-b">
            <li className={`${pathName === 'about' ? '-mb-px' : ''} mr-1`}>
              <Link className={`${pathName === 'about' ? 'border-l border-t border-r rounded-t text-blue-700' : 'text-blue-500 hover:text-blue-800'} bg-slate-900 inline-block  py-2 px-4 font-semibold`} href="/">About Me</Link>
            </li>
            <li className="mr-1">
              <Link className="bg-slate-900 inline-block py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold" href="/projects">Projects</Link>
            </li>
            <li className="mr-1">
              <Link className="bg-slate-900 inline-block py-2 px-4 text-blue-500 hover:text-blue-800 font-semibold" href="/contact">Contact</Link>
            </li>
          </ul>
          <Link href='/' className=''><img src='icon.ico' ></img></Link>
          <h2 className='pr-6'>Zion Griffin's Portfolio</h2>
        </nav>

        {children}
      </body>
    </html>
  )
}
